---
kind: pipeline
type: docker
name: testing

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    image: docker.io/koalaman/shellcheck-alpine:stable
    commands:
      - find \{\{cookiecutter.image_name\}\}/overlay/usr/bin/ -type f | xargs shellcheck

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
type: docker
name: notifications

platform:
  os: linux
  arch: amd64

steps:
  - name: notify
    image: docker.io/plugins/slack
    settings:
      channel:
        from_secret: rocketchat_chat_channel
      webhook:
        from_secret: rocketchat_chat_webhook
    when:
      status:
        - failure

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
  status:
    - success
    - failure

depends_on:
  - testing
